// waysToApplyCss/index.jsx
import React, { useState } from "react";
import { Styled } from "./styled";
import {
    FiChevronDown,
    FiChevronRight,
    FiLink2,
    FiFileText,
    FiLayers,
    FiCode,
    FiSliders,
} from "react-icons/fi";

const WaysToApplyCss = () => {
    const [open, setOpen] = useState(false);

    const toggle = () => setOpen((v) => !v);

    return (
        <Styled.Wrapper className={`topicCard ${open ? "open" : ""}`}>
            <button
                type="button"
                className="topicHeader"
                onClick={toggle}
                aria-expanded={open}
            >
                <span className="chev">
                    {open ? <FiChevronDown /> : <FiChevronRight />}
                </span>

                <span className="icon">
                    <FiLink2 />
                </span>

                <span className="title">Ways to Apply CSS</span>

                <span className="meta">{open ? "Collapse" : "Expand"}</span>
            </button>

            <div className={`topicBody ${open ? "open" : ""}`}>
                <div className="intro">
                    <div className="pill">
                        <span className="pillIcon">
                            <FiLayers />
                        </span>
                        Linking CSS to HTML
                    </div>

                    <p className="p">
                        CSS can be applied in multiple ways. In real projects,
                        external stylesheets are the standard. Inline and
                        internal styles are mainly for quick demos or special
                        cases.
                    </p>
                </div>

                <div className="section">
                    <h3 className="h3">Inline CSS</h3>
                    <p className="p">
                        Styles written directly on an element using the{" "}
                        <span className="mono">style</span> attribute. It is
                        quick but hard to maintain and reuse.
                    </p>

                    <div className="codeBlock">
                        <div className="codeTop">
                            <span className="codeIcon">
                                <FiCode />
                            </span>
                            Example
                        </div>
                        <pre className="code">{`<p style="color: #4ea1ff; margin: 0;">
  Hello CSS
</p>`}</pre>
                    </div>

                    <div className="callout">
                        <div className="calloutTitle">
                            <span className="calloutIcon">
                                <FiSliders />
                            </span>
                            When to use
                        </div>
                        <div className="calloutText">
                            Use inline styles for tiny one-off overrides, or
                            dynamic styling generated by JS. Avoid for normal
                            layout and theme styling.
                        </div>
                    </div>
                </div>

                <div className="section">
                    <h3 className="h3">Internal CSS</h3>
                    <p className="p">
                        CSS written inside a <span className="mono">style</span>{" "}
                        tag in the HTML <span className="mono">head</span>.
                        Works for single pages or prototypes.
                    </p>

                    <div className="codeBlock">
                        <div className="codeTop">
                            <span className="codeIcon">
                                <FiFileText />
                            </span>
                            Example
                        </div>
                        <pre className="code">
                            {`<head>
  <style>
    .card { padding: 16px; border: 1px solid #2d333b; }
  </style>
</head>`}
                        </pre>
                    </div>
                </div>

                <div className="section">
                    <h3 className="h3">External CSS</h3>
                    <p className="p">
                        CSS in a separate <span className="mono">.css</span>{" "}
                        file linked using <span className="mono">link</span>.
                        This is the most maintainable and reusable approach.
                    </p>

                    <div className="codeBlock">
                        <div className="codeTop">
                            <span className="codeIcon">
                                <FiLink2 />
                            </span>
                            Example
                        </div>
                        <pre className="code">
                            {`<head>
  <link rel="stylesheet" href="styles.css" />
</head>`}
                        </pre>
                    </div>

                    <ul className="bullets">
                        <li>
                            <span className="dot" />
                            Best for real projects
                        </li>
                        <li>
                            <span className="dot" />
                            Cached by browser
                        </li>
                        <li>
                            <span className="dot" />
                            Easy to manage at scale
                        </li>
                    </ul>
                </div>

                <div className="section">
                    <h3 className="h3">@import rule</h3>
                    <p className="p">
                        Used inside a CSS file to import another stylesheet.
                        Works, but can be slower and harder to manage than a{" "}
                        <span className="mono">link</span> tag in many cases.
                    </p>

                    <div className="codeBlock">
                        <div className="codeTop">
                            <span className="codeIcon">
                                <FiCode />
                            </span>
                            Example
                        </div>
                        <pre className="code">
                            {`/* in main.css */
@import "./reset.css";
@import "./components/button.css";`}
                        </pre>
                    </div>

                    <p className="p muted">
                        Note: Modern tools (Vite, bundlers) handle imports well,
                        but in plain CSS on web pages, multiple @import can
                        affect loading performance.
                    </p>
                </div>

                <div className="section">
                    <h3 className="h3">Order of precedence</h3>
                    <p className="p">
                        If multiple styles target the same element and property,
                        the browser decides the final value using the cascade. A
                        simple quick order is:
                    </p>

                    <div className="rank">
                        <div className="rankItem">
                            <span className="rankNo">1</span>
                            Inline styles (strongest)
                        </div>
                        <div className="rankItem">
                            <span className="rankNo">2</span>
                            Internal and External (depends on order and
                            specificity)
                        </div>
                        <div className="rankItem">
                            <span className="rankNo">3</span>
                            Browser default styles (weakest)
                        </div>
                    </div>

                    <div className="callout">
                        <div className="calloutTitle">
                            <span className="calloutIcon">
                                <FiLayers />
                            </span>
                            Remember this
                        </div>
                        <div className="calloutText">
                            When specificity is equal, the rule that appears
                            later wins. Inline styles usually beat normal
                            stylesheets.
                        </div>
                    </div>
                </div>
            </div>
        </Styled.Wrapper>
    );
};

export default WaysToApplyCss;
